# example_config.toml
# Example configuration file for synthetic-join-datagen
# CLI arguments override config values.

[data_generation]
relations = 5
attributes = 4
unique-tuples = 10000
duplication-factor = 1
distribution = "zipf"
skew = 2.5
domain-size = 1000
null-percentage = 0.05
data-output-format = "csv"

[plan_generation]
max-join-relations = 5
join-pattern = ["random", "star", "chain", "cyclic"]
plan-granularity = ["table", "attribute"]
plan-output-format = ["txt", "json"]
generate-dot-visualization = true

[common]
seed = 12345
base-output-dir = "generated_output_dask"
data-subdir = "data"
plan-subdir = "plans"

[dask]
workers = 4
threads-per-worker = 2
memory-limit = "2GB"
num-data-partitions-per-relation = 4

[logging]
verbose = false
log-file = "logs/datagen.log"

[analysis]
run-analysis = true
