[data_generation]
relations = 10
attributes = 7
unique-tuples = 1000
duplication-factor = 1
distribution = "normal"
domain-size = 500
null-percentage = 0.1
data-output-format = "csv"

[plan_generation]
plans = 2
join-pattern = ["random", "star"]
plan-granularity = ["table", "attribute"]
plan-output-format = ["txt"]
generate-dot-visualization = true

[common]
seed = 42
verbose = 2